// 1. Filtros Principales
export enum MainFilter {
  Featured = "featured",
  Top = "top",
  New = "new",
  Hot = "hot",
}

// 2. Tipos de Producto
export enum ProductType {
  Prompts = "Prompts",
  Bundles = "Bundles",
  Apps = "Apps",
  All = "All",
}

// 3. Tipos
export enum TypeFilter {
  All = "All",
  Image = "Image",
  Text = "Text",
}

// 4. Ordenar por
export enum SortBy {
  Trending = "Trending",
  MostPopular = "Most Popular",
  Newest = "Newest",
}

// 5. Modelos
export enum Model {
  All = "All",
  DALL_E = "DALL·E",
  Claude = "Claude",
  FLUX = "FLUX",
  Gemini = "Gemini",
  GPT = "GPT",
  Ideogram = "Ideogram",
  LeonardoAi = "Leonardo Ai",
  Llama = "Llama",
  Midjourney = "Midjourney",
  Mistral = "Mistral",
  StableDiffusion = "Stable Diffusion",
}

// 6. Categorías
export enum Category {
  All = "All",
  ThreeD = "3D",
  Accessory = "Accessory",
  Ads = "Ads",
  Animal = "Animal",
  Anime = "Anime",
  Art = "Art",
  Avatar = "Avatar",
  Building = "Building",
  Business = "Business",
  Cartoon = "Cartoon",
  Celebrity = "Celebrity",
  Chatbot = "Chatbot",
  Clothes = "Clothes",
  Coach = "Coach",
  Code = "Code",
  Conversion = "Conversion",
  Copy = "Copy",
  Cute = "Cute",
  Cyberpunk = "Cyberpunk",
  Drawing = "Drawing",
  Drink = "Drink",
  Email = "Email",
  Fantasy = "Fantasy",
  Fashion = "Fashion",
  Finance = "Finance",
  Fix = "Fix",
  Food = "Food",
  Fun = "Fun",
  Funny = "Funny",
  Future = "Future",
  Games = "Games",
  Generation = "Generation",
  Glass = "Glass",
  GraphicDesign = "Graphic Design",
  Health = "Health",
  Holiday = "Holiday",
  Icons = "Icons",
  Ideas = "Ideas",
  Illustration = "Illustration",
  Ink = "Ink",
  Interiors = "Interiors",
  Jewelry = "Jewelry",
  Landscape = "Landscape",
  Language = "Language",
  Logo = "Logo",
  Marketing = "Marketing",
  Mockup = "Mockup",
  Monogram = "Monogram",
  Monster = "Monster",
  Music = "Music",
  Nature = "Nature",
  Painting = "Painting",
  Pattern = "Pattern",
  People = "People",
  Photography = "Photography",
  PixelArt = "Pixel Art",
  Plan = "Plan",
  Product = "Product",
  Psychedelic = "Psychedelic",
  Retro = "Retro",
  Scary = "Scary",
  SEO = "SEO",
  Social = "Social",
  Space = "Space",
  Sport = "Sport",
  Statues = "Statues",
  Steampunk = "Steampunk",
  Study = "Study",
  UniqueStyle = "Unique Style",
  Summarise = "Summarise",
  Synthwave = "Synthwave",
  Texture = "Texture",
  Translate = "Translate",
  Travel = "Travel",
  Vehicle = "Vehicle",
  Wallpaper = "Wallpaper",
  Wood = "Wood",
  Writing = "Writing",
  Enterprise = "Enterprise",
  Movie = "Movie",
  Market = "Market",
}

// 7. Categorías Generales
export enum GeneralCategory {
  Creative = "Creative",
  Technical = "Technical",
  Lifestyle = "Lifestyle",
  Business = "Business",
  Entertainment = "Entertainment",
  Others = "Others",
}

// Agrupación de Categorías bajo Categorías Generales
export const GeneralCategoryMap: { [key in GeneralCategory]: Category[] } = {
  [GeneralCategory.Creative]: [
    Category.Art,
    Category.Anime,
    Category.Drawing,
    Category.Painting,
    Category.GraphicDesign,
    Category.Illustration,
    Category.PixelArt,
    Category.Texture,
    Category.Cyberpunk,
    Category.Retro,
    Category.Synthwave,
    Category.Steampunk,
    Category.Fantasy,
    Category.Music,
  ],
  [GeneralCategory.Technical]: [
    Category.Code,
    Category.Marketing,
    Category.SEO,
    Category.Translate,
    Category.Finance,
  ],
  [GeneralCategory.Lifestyle]: [
    Category.Fashion,
    Category.Health,
    Category.Food,
    Category.Drink,
    Category.Writing,
    Category.Travel,
    Category.Interiors,
  ],
  [GeneralCategory.Business]: [
    Category.Business,
    Category.Marketing,
    Category.Enterprise, // Añadir si existe
  ],
  [GeneralCategory.Entertainment]: [
    Category.Games,
    Category.Celebrity,
    Category.Movie, // Añadir si existe
    Category.Social,
  ],
  [GeneralCategory.Others]: [
    Category.All,
    Category.Ads,
    Category.Accessory,
    Category.Cyberpunk,
    Category.Chatbot,
    Category.Clothes,
    Category.Coach,
    Category.Conversion,
    Category.Copy,
    Category.Cute,
    Category.Fix,
    Category.Fun,
    Category.Funny,
    Category.Future,
    Category.Games,
    Category.Generation,
    Category.Glass,
    Category.Health,
    Category.Holiday,
    Category.Icons,
    Category.Ideas,
    Category.Ink,
    Category.Interiors,
    Category.Jewelry,
    Category.Landscape,
    Category.Language,
    Category.Logo,
    Category.Market,
    Category.Mockup,
    Category.Monogram,
    Category.Monster,
    Category.Nature,
    Category.People,
    Category.Photography,
    Category.Plan,
    Category.Product,
    Category.Psychedelic,
    Category.Retro,
    Category.Scary,
    Category.Social,
    Category.Space,
    Category.Sport,
    Category.Statues,
    Category.Steampunk,
    Category.Study,
    Category.UniqueStyle,
    Category.Summarise,
    Category.Synthwave,
    Category.Texture,
    Category.Translate,
    Category.Travel,
    Category.Vehicle,
    Category.Wallpaper,
    Category.Wood,
    Category.Writing,
  ],
};

// 8. Tags
export enum Tag {
  AI = "AI",
  Design = "Design",
  Marketing = "Marketing",
  Technology = "Technology",
  Lifestyle = "Lifestyle",
  Entertainment = "Entertainment",
  Business = "Business",
  Education = "Education",
  Health = "Health",
  Finance = "Finance",
  Creative = "Creative",
  Fun = "Fun",
  Nature = "Nature",
  Fantasy = "Fantasy",
  // Agrega más tags según sea necesario
}

// Lista completa de Tags
export const Tags: Tag[] = [
  Tag.AI,
  Tag.Design,
  Tag.Marketing,
  Tag.Technology,
  Tag.Lifestyle,
  Tag.Entertainment,
  Tag.Business,
  Tag.Education,
  Tag.Health,
  Tag.Finance,
  Tag.Creative,
  Tag.Fun,
  Tag.Nature,
  Tag.Fantasy,
];
